version: '3.8'

services:
  api:
    build: .
    image: bodega-api:1.0.0
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_USER: ${MYSQL_DOCKER_USER}
      MYSQL_PASSWORD: ${MYSQL_DOCKER_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
