openapi: 3.0.0
info:
  title: Bodega API
  description: Esta é a documentação da Bodega API.
  version: 1.0.0

paths:
  # --- Auth ---
  /api/auth/login:
    post:
      summary: Retorna o token
      description: Retorna o token do usuário
      tags:
        - Autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'teste@email.com'
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: Usuários encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Login realizado com sucesso.'
                  token:
                    type: string
                    example: 'jwt-token-here'

  # --- Users ---
  /api/users/:
    get:
      summary: Retorna uma lista de usuários
      description: Retorna uma lista de usuários cadastrados no sistema
      tags:
        - Usuários
      responses:
        '200':
          description: Usuários encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: boolean
                    example: 'Usuários encontrados com sucesso.'
                  data:
                    type: array
                    items:
                      type: object

  # --- Products ---
  /api/products:
    get:
      summary: Retorna uma lista de produtos
      description: Retorna uma lista de todos os produtos disponíveis no sistema
      tags:
        - Produtos
      responses:
        '200':
          description: Produtos encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Produtos encontrados com sucesso.'
                  data:
                    type: array
                    items:
                      type: object

  /api/products/{id}:
    get:
      summary: Retorna um produto
      description: Retorna um produto disponíveis no sistema
      tags:
        - Produtos
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object

  # --- Orders ---
  /api/orders:
    get:
      summary: Retorna uma lista de pedidos
      description: Retorna todos os pedidos no sistema
      tags:
        - Pedidos
      responses:
        '200':
          description: Pedidos encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Pedidos encontrados com sucesso.'
                  data:
                    type: array
                    items:
                      type: object

    post:
      summary: Cadastra um pedido
      description: Retorna o pedido cadastrado no sistema
      tags:
        - Pedidos
      responses:

  /details/{orderId}:
    get:
      summary: Retorna os detalhes do pedido
      description: Retorna os detalhes do pedido no sistema
      tags:
        - Pedidos
      responses:

  /api/orders/{orderId}:
    put:
      summary: Atualiza um pedido
      description: Retorna o pedido no sistema
      tags:
        - Pedidos
      responses:
