openapi: 3.0.0
info:
  title: Bodega API
  description: Esta é a documentação da Bodega API.
  version: 1.0.0

paths:
  # --- Auth ---
  /api/auth/login:
    post:
      summary: Executa o login
      description: Retorna o token do usuário
      tags:
        - Autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'user@example.com'
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: Usuários encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Login realizado com sucesso.'
                  token:
                    type: string
                    example: 'jwt-token-here'

  # --- Users ---
  /api/users/:
    get:
      summary: Retorna uma lista de usuários
      description: Retorna uma lista com os dados dos usuários cadastrados no sistema
      tags:
        - Usuários
      responses:
        '200':
          description: Usuários encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: boolean
                    example: 'Usuários encontrados com sucesso.'
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        password:
                          type: string
                        status:
                          type: string

    post:
      summary: Cadastra um usuário
      description: Retorna os dados do usuário cadastrado no sistema
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':

  /api/users/user:
    get:
      summary: Retorna uma lista de dados do usuário
      description:  Retorna uma lista de dados do usuário no sistema
      tags:
        - Usuários
      responses:

  /api/users/update:
    put:
      summary: Atualiza o usuário
      description: Retorna os dados do usuário atualizado no sistema
      tags:
        - Usuários
      responses:

  #  --- Products ---
  /api/products:
    get:
      summary: Retorna uma lista de produtos
      description: Retorna uma lista de todos os produtos disponíveis no sistema
      tags:
        - Produtos
      responses:
        '200':
          description: Produtos encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Produtos encontrados com sucesso.'
                  data:
                    type: array
                    items:
                      type: object

    post:
      summary: Cadastra um produto
      description: Retorna os dados do produto cadastrado no sistema
      tags:
        - Produtos
      responses:

  /api/products/{productId}:
    get:
      summary: Retorna um produto
      description: Retorna os dados do produto no sistema
      tags:
        - Produtos
      parameters:
        - name: productId
          in: path
          required: true
          description: ID do produto
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object

    put:
      summary: Retorna o produto atualizado
      description: Retorna os dados do produto atualizado no sistema
      tags:
        - Produtos
      responses:

  # --- Orders ---
  /api/orders:
    get:
      summary: Retorna uma lista de todos os pedidos
      description: Retorna uma lista com os dados dos pedidos no sistema
      tags:
        - Pedidos
      responses:
        '200':
          description: Pedidos encontrados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Pedidos encontrados com sucesso.'
                  data:
                    type: array
                    items:
                      type: object

    post:
      summary: Cadastra um pedido
      description: Retorna os dados do pedido cadastrado no sistema
      tags:
        - Pedidos
      responses:

  /api/orders/user:
    get:
      summary: Retorna uma lista de todos os pedidos do usuário
      description: Retorna uma lista com os dados de todos os pedidos do usuário no sistema
      tags:
        - Pedidos
      responses:

  /details/{orderId}:
    get:
      summary: Retorna os detalhes do pedido
      description: Retorna os dados dos detalhes do pedido no sistema
      tags:
        - Pedidos
      responses:

  /api/orders/{orderId}:
    put:
      summary: Atualiza um pedido
      description: Retorna os dados do pedido atualizado no sistema
      tags:
        - Pedidos
      responses:
