CREATE TABLE IF NOT EXISTS addresses (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	street VARCHAR(100) NOT NULL,
	number INT NOT NULL,
	neighborhood VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	state CHAR(2) NOT NULL,
	postal_code CHAR(8) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
