CREATE TABLE IF NOT EXISTS products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	price DECIMAL(10, 2) NOT NULL,
	description TEXT NOT NULL,
	stock INT UNSIGNED NOT NULL DEFAULT 0,
	status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
	image_path VARCHAR(200) DEFAULT 'default_image.png',
	views INT NOT NULL DEFAULT 0,
	purchases INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
