CREATE TABLE IF NOT EXISTS addresses (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL, 
	street VARCHAR(200) NOT NULL,
	number INT NOT NULL,
	neighborhood VARCHAR(200) NOT NULL,
	city VARCHAR(200) NOT NULL,
	state CHAR(2) NOT NULL,
	zip_code CHAR(8) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
