CREATE TABLE IF NOT EXISTS products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(200) NOT NULL, 
	price DECIMAL(10, 2) NOT NULL,
	description TEXT NOT NULL,
	stock INT UNSIGNED NOT NULL DEFAULT 10,
	image_path VARCHAR(200) DEFAULT 'default_image.png',
	status ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
